// <auto-generated />
using System;
using ERP.DAL.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.DAL.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20220302070846_Initial_V1")]
    partial class Initial_V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ERP.Entities.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"), 1L, 1);

                    b.Property<int>("BuyOrderOrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("BidId");

                    b.HasIndex("BuyOrderOrderId");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("ERP.Entities.Models.BuyOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("SupplyTermsContractId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("SupplyTermsContractId");

                    b.ToTable("BuyOrder");
                });

            modelBuilder.Entity("ERP.Entities.Models.Dealer", b =>
                {
                    b.Property<int>("DealerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DealerId"), 1L, 1);

                    b.Property<string>("DealerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DealerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DealerId");

                    b.HasIndex("UserId");

                    b.ToTable("Dealer");
                });

            modelBuilder.Entity("ERP.Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ERP.Entities.Models.ProductDemand", b =>
                {
                    b.Property<int>("DemandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DemandId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("DemandId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDemand");
                });

            modelBuilder.Entity("ERP.Entities.Models.ProductDetail", b =>
                {
                    b.Property<int>("ProductDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDetailId"), 1L, 1);

                    b.Property<int>("Aesthetic")
                        .HasColumnType("int");

                    b.Property<int>("Innovation")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Usability")
                        .HasColumnType("int");

                    b.HasKey("ProductDetailId");

                    b.ToTable("ProductDetail");
                });

            modelBuilder.Entity("ERP.Entities.Models.ProductQualityDetails", b =>
                {
                    b.Property<int>("QualityDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualityDetailId"), 1L, 1);

                    b.Property<int>("Aesthetic")
                        .HasColumnType("int");

                    b.Property<int>("Innovation")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Usability")
                        .HasColumnType("int");

                    b.HasKey("QualityDetailId");

                    b.ToTable("ProductQualityDetails");
                });

            modelBuilder.Entity("ERP.Entities.Models.SupplyTermsContract", b =>
                {
                    b.Property<int>("SupplyTermsContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplyTermsContractId"), 1L, 1);

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.HasKey("SupplyTermsContractId");

                    b.ToTable("SupplyTermsContract");
                });

            modelBuilder.Entity("ERP.Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ERP.Entities.Models.Bid", b =>
                {
                    b.HasOne("ERP.Entities.Models.BuyOrder", "BuyOrder")
                        .WithMany("Bid")
                        .HasForeignKey("BuyOrderOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyOrder");
                });

            modelBuilder.Entity("ERP.Entities.Models.BuyOrder", b =>
                {
                    b.HasOne("ERP.Entities.Models.SupplyTermsContract", "SupplyTermsContract")
                        .WithMany("BuyOrder")
                        .HasForeignKey("SupplyTermsContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplyTermsContract");
                });

            modelBuilder.Entity("ERP.Entities.Models.Dealer", b =>
                {
                    b.HasOne("ERP.Entities.Models.User", "User")
                        .WithMany("Dealer")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP.Entities.Models.ProductDemand", b =>
                {
                    b.HasOne("ERP.Entities.Models.Product", "Product")
                        .WithMany("ProductDemand")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Entities.Models.BuyOrder", b =>
                {
                    b.Navigation("Bid");
                });

            modelBuilder.Entity("ERP.Entities.Models.Product", b =>
                {
                    b.Navigation("ProductDemand");
                });

            modelBuilder.Entity("ERP.Entities.Models.SupplyTermsContract", b =>
                {
                    b.Navigation("BuyOrder");
                });

            modelBuilder.Entity("ERP.Entities.Models.User", b =>
                {
                    b.Navigation("Dealer");
                });
#pragma warning restore 612, 618
        }
    }
}
